[program:Openbox]
command=bash -c 'mkdir -p $HOME/.config/openbox && cp -f /config/openbox/rc.xml $HOME/.config/openbox/rc.xml 2>/dev/null; exec openbox --config-file /config/openbox/rc.xml'

priority=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
