[program:Chromium]
command=bash -c 'mkdir -p /data/google-chrome
  touch "/data/google-chrome/First Run"
  RES=$(jq --raw-output ".resolution // \"1024x768\"" /data/options.json 2>/dev/null)
  W=$(echo "$RES" | cut -d"x" -f1)
  H=$(echo "$RES" | cut -d"x" -f2)
  URL=$(jq --raw-output ".url // \"http://homeassistant:8123\"" /data/options.json 2>/dev/null)
  exec chromium --kiosk --no-sandbox --test-type --no-first-run --disable-dev-shm-usage --start-maximized --window-position=0,0 --window-size=${W:-1024},${H:-768} --force-device-scale-factor=1 --noerrdialogs --user-data-dir=/data/google-chrome "$URL"'
priority=5
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
